config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'photos#index'
  get '/upload', to: 'photos#new'
  post '/photos', to: 'photos#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
    mount_uploader :image, PhotoUploader
    validates_presence_of :title, :description, :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:success] = 'Photo Created successfully'
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :description, :votes, :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IbmCloudStorageExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/index.html.erb
<% @photos.each do |photo| %>
  <ul>
    <li><%= photo.title %></li>
    <li><%= photo.description %></li>
    <li><%= photo.votes %></li>
    <%= image_tag photo.image.url if !photo.image.url.nil? %>
  </ul>
<% end%>

<%= link_to "Create new", upload_path %>

app/views/photos/new.html.erb
<%= form_with(model: @photo, local: true, html: { multipart: true }) do |form| %>
    <% if @photo.errors.any? %>
        <div>
            <h2><%= pluralize(@photo.errors.count, "error") %></h2>
            <ul>
                <% @photo.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div class="field">
        <%= form.label :description %>
        <%=form.text_field :description %>
    </div>

    <div class="field">
        <%= form.label :votes %>
        <%= form.number_field :votes%>
    </div>

    <div class="field">
        <%= form.label :image, 'Upload the foto' %>
        <%= form.file_field :image %>
    </div>

    <%= form.hidden_field :image_cache %>

    <div class="actions">
        <%= form.submit "Upload Your photo" %>
    </div>

<% end %>